package de.uni_koblenz.enums;

public enum PartOfSpeechTypes {
	COORDINATING_CONJUNCTION("CC"), 
	CARDINAL_NUMBER("CD"), 
	DETERMINER("DT"), 
	EXISTENTIAL_THERE("EX"), 
	FOREIGN_WORD("FW"), 
	PREPOSITION_SUBORDINATING_CONJUNCTION("IN"), 
	ADJECTIVE("JJ"),
	ADJECTIVE_COMPARATIVE("JJR"), 
	ADJECTIVE_SUPERLATIVE("JJS"), 
	LIST_ITEM_MARKER, 
	MODAL, 
	NOUN_SINGULAR_MASS("NN"), 
	NOUN_PLURAL("NNS"), 
	PROPER_NOUN_SINGULAR("NNP"),
	PROPER_NOUN_PLURAL("NNPS"), 
	PREDETERMINER("PDT"), 
	POSSESSIVE_ENDING, 
	PERSONAL_PRONOUN("PRP"), 
	POSSESSIVE_PRONOUN(), 
	ADVERB("RB"), 
	ADVERB_COMPARATIVE("RBR"), 
	ADVERB_SUPERLATIVE("RBS"),
	PARTICLE("RP"), 
	SYMBOL("SYM"), 
	TO("TO"), 
	INTERJECTION("UH"), 
	VERB_BASE("VB"), 
	VERB_PAST("VBD"), 
	VERB_GERUND_OR_PRESENT_PARTICIPLE("VBG"), 
	VERB_PAST_PARTICIPLE("VBN"),
	VERB_NON_3RD_PERSON_SINGULAR_PRESENT("VBP"), 
	VERB_3RD_PERSON_SINGULAR_PRESENT("VBZ"), 
	WH_DETERMINER("WDT"), 
	WH_PRONOUN("WP"), 
	POSSESSIVE_WH_PRONOUN,
	WH_ADVERB("WRB"),
	NOUN_PHRASE("NP"), 
	PREPOSITIONAL_PHRASE("PP"), 
	VERB_PHRASE("VP");
	
	
	private String shortType;
	
	private PartOfSpeechTypes() {
		
	}
	
	private PartOfSpeechTypes(String shortType) {
		this.shortType = shortType;
	}
	
	public String getShortType() {
		return this.shortType;
	}
}
