package de.uni_koblenz.enums;

public enum PartOfSpeechTypes {
	COORDINATING_CONJUNCTION, CARDINAL_NUMBER, DETERMINER, EXISTENTIAL_THERE, FOREIGN_WORD, PREPOSITION_SUBORDINATING_CONJUNCTION, ADJECTIVE,
	ADJECTIVE_COMPARATIVE, ADJECTIVE_SUPERLATIVE, LIST_ITEM_MARKER, MODAL, NOUN_SINGULAR_MASS, NOUN_PLURAL, PROPER_NOUN_SINGULAR,
	PROPER_NOUN_PLURAL, PREDETERMINER, POSSESSIVE_ENDING, PERSONAL_PRONOUN, POSSESSIVE_PRONOUN, ADVERB, ADVERB_COMPARATIVE, ADVERB_SUPERLATIVE,
	PARTICLE, SYMBOL, TO, INTERJECTION, VERB_BASE, VERB_PAST, VERB_GERUND_OR_PRESENT_PARTICIPLE, VERB_PAST_PARTICIPLE,
	VERB_NON_3RD_PERSON_SINGULAR_PRESENT, VERB_3RD_PERSON_SINGULAR_PRESENT, WH_DETERMINER, WH_PRONOUN, POSSESSIVE_WH_PRONOUN,
	WH_ADVERB
}
