package de.uni_koblenz.enums;

public enum PhraseStructureTypes {
	VI("VERB_IMPERATIVE"),
	VB("VERB_BASE"),
	VP("VERB_PASSIVE"),
	VPP("VERB_PASSIVE_PAST"),
	VPrP("VERB_PRESENT_PARTICIPLE"),
	VSP("VERB_SIMPLEPAST"),
	VSF("VERB_SIMPLEFUTURE"),
	NSO("NOUN_SINGULAR_OBJECT"),
	NSS("NOUN_SINGULAR_SUBJECT"),
	NPO("NOUN_PLURAL_OBJECT"),
	NPS("NOUN_PLURAL_SUBJECT"),
	DetDef("DETERMINER_DEFINITEARTICLE"),
	DetIndef("DETERMINER_INDEFINITEARTICLE"),
	PP("PUNCTUATION_PERIOD"),
	PQ("PUNCTUATION_QUESTIONMARK"),
	AO("ADJECTIVE_FOR_OBJECT"),
	AS("ADJECTIVE_FOR_SUBJECT"),
	APO("ADJECTIVE_FOR_PREPOSITIONAL_OBJECT"),
	ADV("ADVERB"),
	Prep("PREPOSITION"),
	POS("PREPOSITIONAL_OBJECT_SINGULAR"),
	POP("PREPOSITIONAL_OBJECT_PLURAL");

	
	private String determiner;
	
	private PhraseStructureTypes (String determiner) {
		this.determiner = determiner;
	}
	public String getdeterminer() {
		return this.determiner;
	}
}
